# Generated by Django 2.0.6 on 2018-06-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='humans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField()),
                ('round', models.IntegerField()),
                ('humanOne', models.IntegerField()),
                ('humanTwo', models.IntegerField()),
            ],
        ),
    ]
