# Generated by Django 2.0.6 on 2018-06-06 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humans',
            name='humanTwo',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
