# Generated by Django 2.0.6 on 2018-06-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_humansrobot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humans',
            old_name='humanOne',
            new_name='PlayerOne',
        ),
        migrations.RenameField(
            model_name='humans',
            old_name='humanTwo',
            new_name='PlayerTwo',
        ),
        migrations.RenameField(
            model_name='humansrobot',
            old_name='Computer',
            new_name='PlayerOne',
        ),
        migrations.RenameField(
            model_name='humansrobot',
            old_name='human',
            new_name='PlayerTwo',
        ),
    ]
