# Generated by Django 2.0.6 on 2018-06-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_auto_20180613_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='humansrobot',
            name='Model_Used',
            field=models.CharField(default='Random_Model', max_length=20),
            preserve_default=False,
        ),
    ]
