# Generated by Django 2.0.5 on 2018-07-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_humansrobot_model_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humansrobot',
            name='Model_Used',
            field=models.CharField(max_length=15),
        ),
    ]
