# Generated by Django 2.0.6 on 2018-07-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_humansrobot_model_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='humansrobot',
            name='Pseudo_player',
            field=models.CharField(default='ibrahim', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='humansrobot',
            name='Model_Used',
            field=models.CharField(max_length=15),
        ),
    ]
