# Generated by Django 2.0.5 on 2018-07-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_auto_20180716_1025'),
        ('backoffice', '0009_auto_20180712_2145'),
    ]

    operations = [
    ]
