# Generated by Django 2.0.7 on 2018-07-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_humansrobot_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humansrobot',
            old_name='PlayerOne',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='humansrobot',
            old_name='part',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='humansrobot',
            old_name='PlayerTwo',
            new_name='opponent',
        ),
    ]
